import { Metadata } from 'next'
import PrivacyPage from '@/app/components/Privacy'

export const metadata: Metadata = {
  title: 'SDS | Privacy',
  description: 'Generated by create next app',
}

export default function Privacy() {
  return <PrivacyPage />
}
